### ISSUE TITLE
Update README.md - Installation step

### ISSUE THREAD

**Issue by iamunnip** [k0sproject/k0smotron#116]
Hi,

Recently I followed the GitHub README.md to install k0smotron in my local Kubernetes cluster but it failed to pull image.
I opened an issue #112 and solved by following the installation command from official [doc](https://docs.k0smotron.io/v0.3.1/install/).

Can I open a PR for the below change in README.md file.

Current
`kubectl apply -f https://raw.githubusercontent.com/k0sproject/k0smotron/main/install.yaml`

Change to
`kubectl apply -f https://docs.k0smotron.io/stable/install.yaml`

Thank you.

**Comment by jnummelin** [comment]
> Can I open a PR for the below change in README.md file.

Of course, PRs are always welcome!

**Comment by iamunnip** [comment]
PR #118 merged.
