### ISSUE TITLE
Typo on RBAC verb for ControlPlane controller

### ISSUE THREAD

**Issue by prometherion** [k0sproject/k0smotron#189]
https://github.com/k0sproject/k0smotron/blob/b556b40ccc7a370d74c14b496af750ea211f4af3/internal/controller/controlplane/controlplane_controller.go#L64

It should be `patch`.

**Comment by jnummelin** [comment]
whoopsies. 😄 

This kinda reveals that the controller does not even need the `patch` verb. :)
