### ISSUE TITLE
[question] How do workers communicate with the control plane ? 

### ISSUE THREAD

**Issue by mrik974** [k0sproject/k0smotron#240]
Hi, I'm taking interest in this project, since I started working on a similar project, that I could leave behind if k0smotron answers my needs. 
I understand you're using Konnectivity to handle control plane to node communication. But how do you handle node to control plane communication ? If they're on the same network this is an easy thing but I'd like to have the control planes completely separated from the workers. Have you found a way to get this to work ?

**Comment by jnummelin** [comment]
Closing as answered.

**Comment by hwinkel** [comment]
Sounds like Worker -> Master API Communication (with the API) is not going over the Reverse tunnel? I would rather think that there should be only one Connection required for any Worker <-> Master Communication, preferable over the konnectivity tunnel !??!
