### ISSUE TITLE
Node-to-Node communications?

### ISSUE THREAD

**Issue by kbumsik** [k0sproject/k0smotron#255]
Hi, thank you for this project. It looks very interesting.

I k0smotron emphasis on Edge and Multi-Cloud, so understanding the network architecture and its capability is pretty important.

I see that [Control plane to node](https://kubernetes.io/docs/concepts/architecture/control-plane-node-communication/#control-plane-to-node) communication is archived by using Konnectivity.

However, I cannot find any mentions about node-to-node network. Especially, does k0smotron support adding nodes in different network?

It would be great if k0smotron or k0s offers an option to having nodes in different infrastructure as well. This will make it the true Edge, multi-cloud solution.

[k3s offers such options](https://docs.k3s.io/installation/network-options#distributed-hybrid-or-multicloud-cluster), for example (though it seems experimental)

**Comment by jnummelin** [comment]
> Especially, does k0smotron support adding nodes in different network?

Yes, k0smotron does not really care where and how you add nodes to the controlplane. Naturally, as long as the nodes can connect to the k0smotron managed controlplane.

> It would be great if k0smotron or k0s offers an option to having nodes in different infrastructure as well. This will make it the true Edge, multi-cloud solution.

Yes, k0s does support that: https://docs.k0sproject.io/v1.27.5+k0s.0/configuration/#specnetwork

Basically you need to configure the cluster networking to use Calico and enable wireguard for it with `spec.network.calico.wireguard: true`

**Comment by jnummelin** [comment]
I've actually tested this in a case where one of the "edge" nodes was a VM running on my Mac (NAT'd network) and my Mac was connected to "internet" via a plane wifi while flying over Greenland. :D

**Comment by kbumsik** [comment]
Wow, thank you for quick response!

> I've actually tested this in a case where one of the "edge" nodes was a VM running on my Mac (NAT'd network) and my Mac was connected to "internet" via a plane wifi while flying over Greenland. :D

That's really awesome! Let me try k0s and k0smotron then 👍 . This also sounds like we can do a similar thing by using Cilium CNI....

> Basically you need to configure the cluster networking to use Calico and enable wireguard for it with spec.network.calico.wireguard: true

Alright, it seems that I need to look at k0s documentation closely.

**Comment by jnummelin** [comment]
> Alright, it seems that I need to look at k0s documentation closely.

Yes, that is advisable. :D After all, k0s is what "powers" the actual child clusters, k0smotron is "just" the ClusterAPI provider for that.

**Comment by jnummelin** [comment]
I'll close this as the questions are answered and point of origin established. Feel free to open specific issues if you face any issues doing what you are planning.
