### ISSUE TITLE
Add k0smotron to the pre-defined list of clusterctl providers

### ISSUE THREAD

**Issue by makhov** [k0sproject/k0smotron#292]
The clusterctl command ships with a pre-defined list of provider repositories that allows a simpler “out-of-the-box” user experience.

After having #279 and #286 merged we probably want to be on the list.

Some links:
- Docs: https://cluster-api.sigs.k8s.io/clusterctl/provider-contract#pre-defined-list-of-providers
- Provider's list https://github.com/kubernetes-sigs/cluster-api/blob/main/cmd/clusterctl/client/config/providers_client.go
- Example PR: https://github.com/kubernetes-sigs/cluster-api/pull/7528

**Comment by jlnhnng** [comment]
@makhov I think this is done and can be closed, correct?

**Comment by makhov** [comment]
@jlnhnng yes, it's done
