### ISSUE TITLE
[CAPI] Should `RemoteMachine` ctrl stop and reset k0s on machine delete?

### ISSUE THREAD

**Issue by jnummelin** [k0sproject/k0smotron#310]
When `Machine` get deleted which is "implemented" by a `RemoteMachine`, should the remote machine controller do the following:
- SSH into the machine
- stop k0s
- run reset
- remove finalizer

When the `Machine` itself is finally removed, the CAPI machine controller will remove the respective node from the child cluster API. 

@makhov @juanluisvaladas WDYT?

**Comment by makhov** [comment]
Should it also run `k0s etcd leave` to remove the node from the etcd?
