### ISSUE TITLE
[CAPI] Allow options for `RemoteMachine` Provider to support Teleport or Okta ASA

### ISSUE THREAD

**Issue by jlnhnng** [k0sproject/k0smotron#332]
Currently the `RemoteMachine` Provider uses SSH but enterprises mostly do not use long-living SSH keys. 
Tools like Teleport or Okta offer PAM for SSH which includes authentication before providing a short-living SSH key.

**Comment by makhov** [comment]
How we can do it is to use some user-provided pod with all binaries, secrets and configs and run all cloud-init commands using exec to the pod:
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: RemoteMachine
metadata:
  name: remote-test-0
  namespace: default
spec:
  address: teleport-node-1
  user: ubuntu
  execPodRef:
    name: tsh-pod
    namespace: default
    sshCommandPrefix: "tsh ssh" # or ssh -F /path/to/teleport/ssh_config
```

@jnummelin wdyt?

**Comment by jnummelin** [comment]
Something like this could work:

![image](https://github.com/k0sproject/k0smotron/assets/3205505/8e91062c-3ae3-46f8-b6e6-8b328d35496f)


So essentially k0smotron processes the cloud-init to a form of list of command to execute. We then externalize the actual SSH auth and execution to a Job.
