### ISSUE TITLE
[install] JoinTokenRequest issue

### ISSUE THREAD

**Issue by alecks3474** [k0sproject/k0smotron#335]
Hi,
Thanks a lot for this project. It meets a real need.

I'm following this ["started" guide](https://www.mirantis.com/blog/getting-started-with-k0smotron) and  [documentation](https://docs.k0smotron.io/v0.7.0/join-nodes/)  and I have this error when I try to get the token:

```
error: resource mapping not found for name: "my-token" namespace: "default" from "jointokenrequest-cluster1.yaml": no matches for kind "JoinTokenRequest" in version "k0smotron.io/v1beta1"

ensure CRDs are installed first
```

-  k0smoston () on a single "quick start" k0s controller  up and running  ( v1.28.3+k0s.0 )

```
kubectl --kubeconfig=/etc/k0s/child.conf cluster-info
Kubernetes control plane is running at https://10.xx.xx.xx:30443
CoreDNS is running at https://10.xx.xx.xx:30443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
```

**Comment by alecks3474** [comment]
My bad  PEBCAK

**Comment by jnummelin** [comment]
@alecks3474 Care to share what was the problem? Maybe that's something we can enhance in the docs

**Comment by alecks3474** [comment]
Yes, of course.

I did not use k0sctl to create my single-node cluster but directly on the VM "mothership" with `k0s` command. ( `k0s install controller --single` ) 

So I have two kubeconfig files: one for my k0s single-node cluster, another for the child cluster.


```
kubectl --kubeconfig=/etc/k0s/kubeconfig-parent cluster-info
Kubernetes control plane is running at https://10.xx.xx.xx:6443
```

```
kubectl --kubeconfig=/etc/k0s/child.conf cluster-info
Kubernetes control plane is running at https://10.141.xx.xx:30443
```

I was trying to create my `JoinTokenRequest`  with my child cluster kubeconfig... 🤒 


Thanks again for this amazing project
