### ISSUE TITLE
Cluster port can not be changed from 30443

### ISSUE THREAD

**Issue by matti** [k0sproject/k0smotron#345]
https://docs.k0smotron.io/v0.7.0/resource-reference/#clusterspecservice

says "ExternalAddress defines k0s external address. See https://docs.k0sproject.io/stable/configuration/#specapi" - k0s allows port to be specified but Cluster is always fixed to 30443

**Comment by makhov** [comment]
Sorry, not sure that I got it. Could you show an example of misconfigured resources? 
`spec.service.apiPort` is used both in the Service and the k0s config
