### ISSUE TITLE
`Provider` objects

### ISSUE THREAD

**Issue by jnummelin** [k0sproject/k0smotron#407]
k0smotron installation should create the `Provider` objects for all the providers we currently have.

**Comment by makhov** [comment]
I did some research and looks like it's not needed: other providers don't have it and `clusterctl` creates it automatically on `clusterctl init` run:

```
$ k get providers -n k0smotron -o yaml bootstrap-k0smotron
apiVersion: clusterctl.cluster.x-k8s.io/v1alpha3
kind: Provider
metadata:
  creationTimestamp: "2024-01-09T12:15:42Z"
  generation: 1
  labels:
    cluster.x-k8s.io/provider: bootstrap-k0smotron
    clusterctl.cluster.x-k8s.io: ""
    clusterctl.cluster.x-k8s.io/core: inventory
  name: bootstrap-k0smotron
  namespace: k0smotron
  resourceVersion: "2155448"
  uid: 48e3322c-fdba-422f-a6fd-284aecb41fd3
providerName: k0smotron
type: BootstrapProvider
version: v0.8.0
```

But what we need to do is to add `cluster.x-k8s.io/provider` label: https://cluster-api.sigs.k8s.io/clusterctl/provider-contract#labels
