### ISSUE TITLE
Support Airgapped / Offline environments - Add option to provide a path to k0s binary and airgap image bundle

### ISSUE THREAD

**Issue by jlnhnng** [k0sproject/k0smotron#526]
With clusterctl we can already specify other locations for the providers, as well as image overrides for any container image needed in airgapped environements: https://cluster-api.sigs.k8s.io/clusterctl/configuration.html

To be able to support k0smotron with k0s in airgapped / offline environments, we need the option to also specify the location of the k0s binary and the airgap image bundle in 'K0sControlPlane' and 'K0sWorkerConfig'.

**Comment by makhov** [comment]
It's already supported by k0smotron. 
You can set path to k0s binary using `spec.k0sConfigSpec.downloadURL` and download airgap bundle using `spec.k0sConfigSpec.preStartCommands`

https://docs.k0smotron.io/stable/resource-reference/#k0scontrolplanespeck0sconfigspec
