### ISSUE TITLE
Document k0s persistence

### ISSUE THREAD

**Issue by kbumsik** [k0sproject/k0smotron#650]
Hi, I am experimenting k0smotron to implement multi-tenant k8s with remote workers.

While playing around k0smotron, one thing I noticed is that documentation on [Cluster.spec.persistence](https://docs.k0smotron.io/stable/resource-reference/#clusterspecpersistence) is lacking, while it seems to be important for production deployment.

For example:

- What it actually does - the doc doesn't mention what it persists at all. Just saying "persistence configuration" is very confusing. It seems to mount /var/lib/k0s though.
-  Recommended size and performance of the volume
    - dose it need to be high-performance? Suggested IOPS? What is the expected size of the volume? Does it keep growing? 
    - In case of etcd, [it is easier to figure out the optimal pvc settings.](https://etcd.io/docs/v3.2/platforms/aws/#performancethroughput) However, it is hard to figure out the hardware requirements of k0s control plane instance.
- Maybe also add why it needs a persistent volume. I thought kube-apiserver is stateless.

Since v1 is out, some insights regarding production deployments like this would really helps.

**Comment by nealf** [comment]
I'm in the same situation of not knowing whether it is needed or not for non-ephemeral clusters. If it is necessary, we found that it does not currently work in Standalone mode (at least when replicas >1) because it doesn't use the StatefuleSets persistent volume template correctly. It creates the volume template, but the VolumeMount doesn't use the template name and pods are never created because of that config error.

**Comment by apedriza** [comment]
> I'm in the same situation of not knowing whether it is needed or not for non-ephemeral clusters. If it is necessary, we found that it does not currently work in Standalone mode (at least when replicas >1) because it doesn't use the StatefuleSets persistent volume template correctly. It creates the volume template, but the VolumeMount doesn't use the template name and pods are never created because of that config error.

@nealf thanks for reporting this issue 👍  Fix for it was released in `v.1.12`

**Comment by apedriza** [comment]
> Hi, I am experimenting k0smotron to implement multi-tenant k8s with remote workers.
> 
> While playing around k0smotron, one thing I noticed is that documentation on [Cluster.spec.persistence](https://docs.k0smotron.io/stable/resource-reference/#clusterspecpersistence) is lacking, while it seems to be important for production deployment.
> 
> For example:
> 
> * What it actually does - the doc doesn't mention what it persists at all. Just saying "persistence configuration" is very confusing. It seems to mount /var/lib/k0s though.
> * Recommended size and performance of the volume
>   
>   * dose it need to be high-performance? Suggested IOPS? What is the expected size of the volume? Does it keep growing?
>   * In case of etcd, [it is easier to figure out the optimal pvc settings.](https://etcd.io/docs/v3.2/platforms/aws/#performancethroughput) However, it is hard to figure out the hardware requirements of k0s control plane instance.
> * Maybe also add why it needs a persistent volume. I thought kube-apiserver is stateless.
> 
> Since v1 is out, some insights regarding production deployments like this would really helps.

@kbumsik in `v1.2.0` we have added documentation about persitence. https://docs.k0smotron.io/stable/configuration/#persistence . Thank you for reporting it

**Comment by kbumsik** [comment]
> in v1.2.0 we have added documentation about persitence. https://docs.k0smotron.io/stable/configuration/#persistence . Thank you for reporting it

@apedriza Hi, thank you for the update.
I think this explains enough on what it is and the hardware requirement. Well written!

I will close the issue since the new documentation addresses it.
