### ISSUE TITLE
Unable to upgrade standalone k0s cluster on AWS

### ISSUE THREAD

**Issue by a13x5** [k0sproject/k0smotron#670]
## The issue

Initiated upgrade of standalone (on VMs) k0s cluster on AWS infrastructure `v1.29.6+k0s.0` -> `v1.30.3+k0s.0`.

Upgrade initiated by changing `.spec.version` in the `K0sControlPlane` resource as well as in `.spec.template.spec.version` in the `K0sWorkerConfigTemplate`.

I do have CRs statuses updated (which is counterintuitive, since nothing happened yet) with a new version, for example : 

```bash
kubectl get k0scontrolplane aws-cl-1-cp -o jsonpath="{.status.version}"
v1.30.3+k0s.0
```

But the actual cluster remains on previous version and it stuck in this indefinitely.

## Root cause

After some analysis I noticed that the autopilot's `Plan` resource has **wrong** node names in it:

```yaml
  apiVersion: autopilot.k0sproject.io/v1beta2
  kind: Plan
  metadata:
    creationTimestamp: "2024-08-09T16:38:26Z"
    generation: 1
    name: autopilot
    resourceVersion: "4594"
    uid: 0563012c-9f57-48f6-99e3-d624cdc7fb9c
  spec:
    commands:
    - k0supdate:
        platforms:
          linux-amd64:
            url: https://get.k0sproject.io/v1.30.3+k0s.0/k0s-v1.30.3+k0s.0-amd64
          linux-arm:
            url: https://get.k0sproject.io/v1.30.3+k0s.0/k0s-v1.30.3+k0s.0-arm
          linux-arm64:
            url: https://get.k0sproject.io/v1.30.3+k0s.0/k0s-v1.30.3+k0s.0-arm64
        targets:
          controllers:
            discovery:
              static:
                nodes:
                - aws-cl-1-cp-1
                - aws-cl-1-cp-2
                - aws-cl-1-cp-0
            limits:
              concurrent: 1
        version: v1.30.3+k0s.0
    id: id-aws-cl-1-cp-1723221506
    timestamp: "1723221506"
```

So it uses node names which were given by CAPI

```
  NAME                      CLUSTER    NODENAME                                    PROVIDERID                              PHASE     AGE   VERSION
  aws-cl-1-cp-0             aws-cl-1   ip-10-0-90-234.us-west-1.compute.internal   aws:///us-west-1b/i-00811729183d98794   Running   39m   v1.30.3
  aws-cl-1-cp-1             aws-cl-1   ip-10-0-81-251.us-west-1.compute.internal   aws:///us-west-1b/i-0a8274ae033847b4a   Running   39m   v1.30.3
  aws-cl-1-cp-2             aws-cl-1   ip-10-0-75-41.us-west-1.compute.internal    aws:///us-west-1b/i-0116f1582637d2b7f   Running   39m   v1.30.3
  aws-cl-1-md-jgtpl-jlm64   aws-cl-1   ip-10-0-91-155.us-west-1.compute.internal   aws:///us-west-1b/i-0f59b5d169e8a88b6   Running   39m
```

And not names that are actually present in the cluster:

```
  NAME                                        STATUS   ROLES           AGE   VERSION
  ip-10-0-75-41.us-west-1.compute.internal    Ready    control-plane   29m   v1.29.6+k0s
  ip-10-0-81-251.us-west-1.compute.internal   Ready    control-plane   18m   v1.29.6+k0s
  ip-10-0-90-234.us-west-1.compute.internal   Ready    control-plane   30m   v1.29.6+k0s
  ip-10-0-91-155.us-west-1.compute.internal   Ready    <none>          25m   v1.29.6+k0s
```

This is confirmed by the following error in k0s log:

```
Aug 09 16:41:14 ip-10-0-81-251.us-west-1.compute.internal k0s[4170]: time="2024-08-09 16:41:14" level=info msg="starting to cordon node aws-cl-1-cp-1" component=autopilot controller=ControlNode leadermode=false
object=ControlNode reconciler=cordoning signalnode=aws-cl-1-cp-1
Aug 09 16:41:14 ip-10-0-81-251.us-west-1.compute.internal k0s[4170]: time="2024-08-09 16:41:14" level=error msg="Reconciler error" ControlNode="{aws-cl-1-cp-1 }" component=controller-runtime controller=controlno
de controllerGroup=autopilot.k0sproject.io controllerKind=ControlNode error="failed to get node: Node \"aws-cl-1-cp-1\" not found" name=aws-cl-1-cp-1 namespace= reconcileID="\"b20149ec-44b0-4b69-b45a-f71ec1f056f5\""
```

## Conclusion

k0smotron should use `.status.nodeRef.name` of the `Machine` resource as node name in the `Plan`, not its `.metadata.name` (or whatever is used).

**Comment by jnummelin** [comment]
@a13x5 thanks for detailed analysis. You are absolutely correct it's using wrong node names in this case.

The only thing I'm wondering, why do we even need to specify node names in the `Plan`, couldn't we just use empty selector? @makhov WDYT?

What if we're running controller-only nodes as the CP, in that case there will be no nodename and hence the same logic would not apply. AFAIK  we could also cover this case using just empty selector.

**Comment by makhov** [comment]
Interesting. We use `AUTOPILOT_HOSTNAME` to prevent this kind of situations, but looks like, it doesn't always work as expected. 
@a13x5 could you show us cluster configuration to run some tests? 

> The only thing I'm wondering, why do we even need to specify node names in the Plan, couldn't we just use empty selector?
We can't use empty selector, because sometimes there some "leftover" ControlNode objects in the workload cluster from the controllers that don't exist anymore. Autopilot will get stuck and the `Plan` will never succeed.

It can be addressed by another reconciler, that will maintain `ControlNode` list up to date, but for now I created #673 to use `nodeRef` if it exists to fix the issue.

**Comment by a13x5** [comment]
@makhov Sure thing here is a full yaml (.txt because of GH rules): [k0s-standalone-aws.txt](https://github.com/user-attachments/files/16590378/k0s-standalone-aws.txt)

I also should add that the `ControlNode` has wrong hostname as well (IP is correct though)

```yaml
apiVersion: autopilot.k0sproject.io/v1beta2
kind: ControlNode
metadata:
  annotations:
    autopilot.k0sproject.io/mode: controller+worker
  creationTimestamp: "2024-08-12T17:13:06Z"
  generation: 1
  labels:
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: aws-cl-1-cp-0
    kubernetes.io/os: linux
  name: aws-cl-1-cp-0
  resourceVersion: "470"
  uid: 1c3b5b23-2fd6-4a41-b935-e05bf013cba5
status:
  addresses:
  - address: 10.0.67.254
    type: InternalIP
  - address: aws-cl-1-cp-0
    type: Hostname
```

**Comment by makhov** [comment]
@a13x5 the patch versions of k0s with the proper fix were released recently. 
Could you test k0s upgrade from `v1.29.8+k0s.0` to `v1.30.4+k0s.0`?

**Comment by a13x5** [comment]
I finally tested the upgrade.
`v1.29.8+k0s.0` -> `v1.30.4+k0s.0` works just fine on the same env. 
Thanks for fixing this! 
Closing the issue.
