### ISSUE TITLE
k0smotron and CAPK (Cluster API Provider Kubevirt) provided example currently is NOT working together

### ISSUE THREAD

**Issue by kcao3** [k0sproject/k0smotron#741]
Hello everyone,

I am trying to evaluate how K0smotron can work with Cluster API Provider Kubevirt (CAPK). For installation, I have followed the k0smotron official document and example, which can be found here: https://docs.k0smotron.io/v1.1.0/capi-kubevirt/#creating-a-child-cluster. I have applied the example manifests to k8s management cluster.

However, for some reason I am NOT getting similar as shown in this document:

Expected output:
```
% kubectl get cluster,machine
NAME                                   PHASE         AGE     VERSION
cluster.cluster.x-k8s.io/kubevirt-test Provisioned   22h

NAME                                               CLUSTER         NODENAME                  PROVIDERID                           PHASE     AGE     VERSION
machine.cluster.x-k8s.io/kubevirt-md-mdvns-l2rxb   kubevirt-test   kubevirt-md-mdvns-l2rxb   kubevirt://kubevirt-md-mdvns-l2rxb   Running   22h     v1.27.4
```
Actual output:
```
% kubectl get cluster,machine
NAME                                   PHASE         AGE     VERSION
cluster.cluster.x-k8s.io/kubevirt-test Provisioned   2d18h

NAME                                               CLUSTER         NODENAME                  PROVIDERID                           PHASE         AGE     VERSION
machine.cluster.x-k8s.io/kubevirt-md-rp2rm-v6824   kubevirt-test                                                                  Provisioning  2d18h   v1.30.4
```
I have spent quite some time troubleshooting this example. First, I ran into an issue at which it appeared the CAPK did NOT get called to provision anything on the infrastructure at all. This behavior is similar to what was reported from this issue: https://github.com/k0sproject/k0smotron/issues/372.
     
After removing the annotation `cluster.x-k8s.io/managed-by: k0smotron` from the `KubevirtCluster` manifest, I have made some further progress and it appears CAPK now has started a kubevirt VM pod.

However, it appears the Bootstraped process for the `Machine/kubevirt-md-rp2rm-v6824` is still failing due to missing some critical worker configurations within the K0sWorkerConfigTemplate `kubevirt-test-machine-config`, from the provided example manifest:

```
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: K0sWorkerConfigTemplate
metadata:
  name: kubevirt-test-machine-config
spec:
  template:
    spec:
      version: v1.30.4+k0s.0
      # More details of the worker configuration can be set here
```

```
clusterctl describe cluster kubevirt-test -n k0smotron-demo     
NAME                                                                 READY  SEVERITY  REASON                       SINCE  MESSAGE                                                       
Cluster/kubevirt-test                                                True                                          2d18h                                                                   
├─ClusterInfrastructure - KubevirtCluster/kubevirt-test              True                                          2d18h                                                                                                                                
├─ControlPlane - K0smotronControlPlane/k0s-test-cp                                                                                                                                    
└─Workers                                                                                                                                                                                
  └─MachineDeployment/kubevirt-md                                    False  Warning   WaitingForAvailableMachines  2d18h    Minimum availability requires 1 replicas, current 0 available  
    └─Machine/kubevirt-md-rp2rm-v69824                               True                                          2d18h                                                                   
      └─BootstrapConfig - K0sWorkerConfig/kubevirt-test-machine-config-gmcpr 
```

Has anyone tried this example before with k0smontro and CAPK? If yes, please share with me what exact worker configuration that really needs to be specified in the spec section of the K0sWorkerConfigTemplate `kubevirt-test-machine-config`? 

Thank you so much in advance for your help and support.

**Comment by makhov** [comment]
Hello! 

Could you check the VM status by running?
```
kubectl get vms
```

**Comment by kcao3** [comment]
I think I found the root cause of my issue. My management cluster is currently running in an air-gap environment where the hostname `get.k0s.sh`  is not resolved or reachable. I notice this is currently injected into the Kubevirt VM under cloud-init's userdata  from a k8s secret `kubevirt-test-machine-config-cgslr-userdata'. Is there a way to customize this?

**Comment by makhov** [comment]
You can use the `downloadURL` field to specify the custom URL for k0s binary:
https://docs.k0smotron.io/stable/resource-reference/#k0sworkerconfigtemplatespectemplatespec

**Comment by jnummelin** [comment]
The download URL should mitigate this, pls re-open if the issue persist when using that.
